name: Task - Build & Test

on:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup build dependencies
        uses: "./.github/templates/setup-build"

      - name: Setup rust toolchain
        run: rustup show

      - name: Cache Build artefacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-rust-${{ hashFiles('**/rust-toolchain*') }}
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Build the project
        run: |
          cargo build --workspace --locked

      - name: Run tests
        run: |
          cargo test --features runtime-benchmarks --locked